version: 1.0.{build}
build: off
deploy: off
skip_tags: true
clone_depth: 1
environment:
  matrix:
    - VIM_URL: http://files.kaoriya.net/vim/vim74-kaoriya-win64.zip
    - VIM_URL: http://files.kaoriya.net/vim/2011/vim73-kaoriya-win64-20110306.zip
install:
  - git clone --quiet https://github.com/thinca/vim-themis --branch v1.4.1 --single-branch --depth 1 themis
  - git clone --quiet https://github.com/vim-jp/vital.vim.git vital
  - git clone --quiet https://github.com/haya14busa/vital-vimlcompiler vital-vimlcompiler
  - ps: |
      $zip = $Env:APPVEYOR_BUILD_FOLDER + '\vim.zip'
      $vim = $Env:APPVEYOR_BUILD_FOLDER + '\vim\'
      (New-Object Net.WebClient).DownloadFile($Env:VIM_URL, $zip)
      [Reflection.Assembly]::LoadWithPartialName('System.IO.Compression.FileSystem') > $null
      [System.IO.Compression.ZipFile]::ExtractToDirectory($zip, $vim)
      $Env:THEMIS_VIM = $vim + (Get-ChildItem $vim).Name + '\vim.exe'
before_test:
  - ps: |
      & $Env:THEMIS_VIM --version
test_script:
  - ps: |
      .\themis\bin\themis.bat -r --runtimepath vital --runtimepath vital-vimlcompiler --reporter spec
